### PR TITLE
Fix markdown heading render issue

### PR DESCRIPTION
**Pull request by arun1595**

### CODE REVIEW

**Comment by mvoto** [comment]
I was about to work on a similar PR, great job @arun1595 !
I would also suggest to fix the badges that are also broken.
Please let me know if I can help on anything else for this PR.

**Comment by arun1595** [comment]
@mvoto Ah, missed the badges. Let me fix it :smile:

**Comment by arun1595** [comment]
@mvoto Thanks!

**Comment by seanfcarroll** [comment]
This has been merged: https://github.com/activerecord-hackery/ransack/pull/779 but doesn't include the badges. If a PR is just README skip the CI for now, until [we fix the issue of Ruby 2](https://github.com/activerecord-hackery/ransack/issues/794).

**Comment by seanfcarroll** [comment]
Thanks a lot for this, the issue was eventually addressed by another PR. Keep up the contributions!

**Pull request closed without merging**
