### PR TITLE
Support for Rails 6

### LINKED ISSUE #1021: Rails 6 Support
Need to investigate what changes would be required for Rails 6.

### PR DESCRIPTION
**Pull request by vrodokanakis**
Closes #1021

Rails 6 is still under development and breaking changes are happening even in RC versions.  Just a month a go this pull request https://github.com/rails/rails/pull/36120 was merged after `6.0.0.rc1` was released.

This branch is compatible with latest `6-0-stable` branch , which means it will _probably_ be compatible with Rails `6.0.0.rc2` when its released if no future changes are made.

CI will pass if https://github.com/activerecord-hackery/ransack/issues/1024 is merged.

### CODE REVIEW

**Comment by jscheid** [comment]
I'm getting the following, any ideas?

```
     ArgumentError:
       wrong number of arguments (given 4, expected 3)
     # /home/vagrant/.rvm/gems/ruby-2.5.1/gems/activerecord-6.0.0.rc1/lib/active_record/associations/join_dependency.rb:67:in `initialize'
     # /home/vagrant/.rvm/gems/ruby-2.5.1/bundler/gems/ransack-5e69c062ac1d/lib/ransack/adapters/active_record/context.rb:283:in `new'
     # /home/vagrant/.rvm/gems/ruby-2.5.1/bundler/gems/ransack-5e69c062ac1d/lib/ransack/adapters/active_record/context.rb:283:in `build_joins'
     # /home/vagrant/.rvm/gems/ruby-2.5.1/bundler/gems/ransack-5e69c062ac1d/lib/ransack/adapters/active_record/context.rb:237:in `join_dependency'
     # /home/vagrant/.rvm/gems/ruby-2.5.1/bundler/gems/ransack-5e69c062ac1d/lib/ransack/adapters/active_record/ransack/context.rb:27:in `initialize'
     # /home/vagrant/.rvm/gems/ruby-2.5.1/bundler/gems/ransack-5e69c062ac1d/lib/ransack/adapters/active_record/context.rb:10:in `initialize'
     # /home/vagrant/.rvm/gems/ruby-2.5.1/bundler/gems/ransack-5e69c062ac1d/lib/ransack/adapters/active_record/ransack/context.rb:11:in `new'
     # /home/vagrant/.rvm/gems/ruby-2.5.1/bundler/gems/ransack-5e69c062ac1d/lib/ransack/adapters/active_record/ransack/context.rb:11:in `for_class'
     # /home/vagrant/.rvm/gems/ruby-2.5.1/bundler/gems/ransack-5e69c062ac1d/lib/ransack/context.rb:22:in `for'
     # /home/vagrant/.rvm/gems/ruby-2.5.1/bundler/gems/ransack-5e69c062ac1d/lib/ransack/search.rb:25:in `initialize'
     # /home/vagrant/.rvm/gems/ruby-2.5.1/bundler/gems/ransack-5e69c062ac1d/lib/ransack/adapters/active_record/base.rb:18:in `new'
     # /home/vagrant/.rvm/gems/ruby-2.5.1/bundler/gems/ransack-5e69c062ac1d/lib/ransack/adapters/active_record/base.rb:18:in `ransack'
     # /home/vagrant/.rvm/gems/ruby-2.5.1/gems/activerecord-6.0.0.rc1/lib/active_record/relation/delegation.rb:106:in `public_send'
     # /home/vagrant/.rvm/gems/ruby-2.5.1/gems/activerecord-6.0.0.rc1/lib/active_record/relation/delegation.rb:106:in `block in method_missing'
     # /home/vagrant/.rvm/gems/ruby-2.5.1/gems/activerecord-6.0.0.rc1/lib/active_record/relation.rb:398:in `block in scoping'
     # /home/vagrant/.rvm/gems/ruby-2.5.1/gems/activerecord-6.0.0.rc1/lib/active_record/relation.rb:772:in `_scoping'
     # /home/vagrant/.rvm/gems/ruby-2.5.1/gems/activerecord-6.0.0.rc1/lib/active_record/relation.rb:398:in `scoping'
     # /home/vagrant/.rvm/gems/ruby-2.5.1/gems/activerecord-6.0.0.rc1/lib/active_record/relation/delegation.rb:106:in `method_missing'
```

**Comment by vrodokanakis** [comment]
To help anyone else that wants to try this branch you need 

1. `6-0-stable` Rails branch **and**
2. cherry-pick the commit from #1023 pull request

We are using the above in production successfully.

**Comment by vrodokanakis** [comment]
@seanfcarroll  Ι rebased my branch with latest master and also did a fix for sqlite3 due to different dependencies in Rails 6 (sqlite 1.4 is needed, instead of 1.3) for CI to pass.

**Comment by seanfcarroll** [comment]
Thanks a lot @vrodokanakis !

**Pull request merged**
