### PR TITLE
Fix insecure params error and Add sort_url function.

### PR DESCRIPTION
**Pull request by amatotsuji**
I found error that `Generating a URL from non sanitized request parameters is insecure!`.
It caused by generating url using raw unpermited params.
Rails4 or 5 have strong parameters.
I fixed this problem.

And I add sort_url function.
It is return only url of sort_link.

Please review my code and merge to master.

### CODE REVIEW

**Comment by eluvish** [comment]
+1 on this. Upgraded to Rails 5 and now getting:
`Attempting to generate a URL from non-sanitized request parameters! An attacker can inject malicious data into the generated URL, such as changing the host. Whitelist and sanitize passed parameters to be secure.`

**Comment by jonatack** [comment]
@eluvish Use Ransack master with Rails 5 until a new release is made. This issue has been fixed on Ransack master since a year now.

@amatotsuji Thank you for your pull request! Could you please base it on Ransack master and change the least amount of code?

**Comment by jonatack** [comment]
@amatotsuji My apologies for the delay in responding to your contribution.

**Comment by amatotsuji** [comment]
@johnnyshields 
👍

**Comment by jonatack** [comment]
@amatotsuji Thank you. I believe the "Fix insecure params error" is no longer an issue. Is the `search_params` method needed? If not, perhaps rename this PR "Add `sort_url` view helper" and concentrate on that. It would be good to have a change log entry and tests for the new view helper as well, but I can add them if you don't have time.

**Comment by amatotsuji** [comment]
@jonatack 
I can fix by this weekend. I wish you wait until this weekend.

**Comment by jonatack** [comment]
Happy to, all good.

**Comment by amatotsuji** [comment]
@jonatack 
I recreated a pull request (pull #706).
Could you check my code?

**Pull request closed without merging**
