### PR TITLE
Add ransack context opts config distinct true by default

### PR DESCRIPTION
**Pull request by momer**
Resolves issue [#271](https://github.com/ernie/ransack/issues/271) by enabling distinct: true by default for Context.evaluate

### CODE REVIEW

**Comment by avit** [comment]
This PR is getting old: it also includes additional changes that are outside of what is described here. Do we still want this? If it's relevant I can rebase and update it.

**Comment by seanfcarroll** [comment]
A SQL DISTINCT clause uses a different execution path than a regular query, often a more inefficient one. I think automatically adding a distinct to every query will potentially add overhead and reduce the performance of Ransack.

I think it would be best to retain the current behaviour, and allow the optional addition of DISTINCT when needed. 

I vote to close this without merge. Any opinions? @momer @avit @radar

**Comment by seanfcarroll** [comment]
I'm voting to close this. Any opinions?

**Comment by seanfcarroll** [comment]
Closing due to lack of interest.

**Pull request closed without merging**
