### PR TITLE
Rails 4.2 Self Join associations query

### PR DESCRIPTION
**Pull request by miscelatore**
Given these associations...

class User < ActiveRecord::Base
  has_many :orders
  
  has_many :followers, through: :follower_follows, source: :follower
  has_many :follower_follows, foreign_key: :followee_id, class_name: "Follow"
  
  has_many :followees, through: :followee_follows, source: :followee
  has_many :followee_follows, foreign_key: :follower_id, class_name: "Follow"  
end

class Order < ActiveRecord::Base
  belongs_to :user
end

... and a controller...

class OrdersController < ApplicationController
  def index
    @q = Order.ransack(params[:q])
    @orders = @q.result.includes(:user, :followees)
  end
end

... in my views ...

<%= search_form_for @q do |f| %>
  <%= f.label :user_id_eq %>
  <%= f.search_field :user_id_eq %>

  <%= f.submit "search" %>
<% end %>

I've this scenario:

User with ID = 1 => manager role
User with ID = 2 => follower of user_id=1
User with ID = 3 => follower of user_id=1

Below an example of the data contained in the follows table:

 id | follower_id | followee_id |         created_at         |         updated_at         
----+-------------+-------------+----------------------------+----------------------------
  1 |           2 |           1 | 2017-12-09 22:30:03.299006 | 2017-12-09 22:30:03.299006
  2 |           3 |           1 | 2017-12-09 22:30:03.304564 | 2017-12-09 22:30:03.304564
  

Howto setup ransack to find by f.search_field: user_id_eq all order items owned by user_id = 1 and all orders items owned by of user_id = 2 and user_id = 3 ?

After some investigation I've try with this command and it's seems to work:

Order.ransack(user_followees_id_eq: 1).result

### CODE REVIEW

**Comment by seanfcarroll** [comment]
Looks like a really great PR, any chance of cleaning it up? @miscelatore

**Comment by seanlinsley** [comment]
@seanfcarroll assuming the tests pass, you should be able to cherry pick the individual commit:
```sh
# on master
git cherry-pick 6e244222693f5795f16e7d65115348ac9cc44ebb
```

**Comment by seanfcarroll** [comment]
The cheery pick approach is not working, @miscelatore any chance of taking a look at this?

**Comment by seanfcarroll** [comment]
Replaced by https://github.com/activerecord-hackery/ransack/pull/877

**Pull request closed without merging**
