### PR TITLE
Disable ActionView::Helpers::Tags monkey patch on Rails 5

### PR DESCRIPTION
**Pull request by ybart**
https://github.com/rails/rails/commit/530b5fea8f3e04c45a20ff3dcc8d473a6d25c1b4#diff-1b43bc32bcc4987e19cfb3ba2c1c7733

### CODE REVIEW

**Comment by al2o3cr** [comment]
We've run into the same issue trying out Rails master (yay ActiveStorage).

It would be more in keeping with the way version-switching is done to check `ActionView::VERSION::STRING` - `Rails` may not have been loaded yet. 

The regex check also hits the wrong versions - it removes the patch for 5.0 and 5.1 which need it, and adds it back for Rails >= 6. The codebase standard would be something like `::ActionView::VERSION::STRING >= Constants::RAILS_5_2`.

**Comment by ybart** [comment]
I agree. This has been done quickly. I will need to make this cleanly.

**Comment by seanfcarroll** [comment]
@ybart I'm thinking this is no longer an issue and this PR can be closed. What do you think?

**Comment by seanfcarroll** [comment]
Closing as unneeded.

**Pull request closed without merging**
