### PR TITLE
allowing ':wants_array' to be passed as 'false' in predicate options

### PR DESCRIPTION
**Pull request by Pavling**
Addressing https://github.com/activerecord-hackery/ransack/issues/32

### CODE REVIEW

**Comment by jonatack** [comment]
@Pavling this looks good. Could you rebase against master?

**Comment by Pavling** [comment]
Cheers, Rebased and pushed back up to my fork's branch.

**Comment by jonatack** [comment]
Awesome job. Nice touch, using `fetch`. Thanks for adding missing tests that we didn't have, in addition to testing this feature and for adding specs for both Mongoid and Active Record.

**Comment by jonatack** [comment]
Fixes #32.

**Pull request merged**
