### PR TITLE
Fix NoMethodError in casted_array_with_in_predicate?

### PR DESCRIPTION
**Pull request by jaredbeck**
This failing test reproduces https://github.com/activerecord-hackery/ransack/issues/504

It's a much-simplified version of a ransacker in my application which worked in 1.5.1 and 1.6.0, but which fails in subsequent releases, including master, because of https://github.com/activerecord-hackery/ransack/commit/6c59e96adaa43f4e8141352f508b84a046343591 as explained in https://github.com/activerecord-hackery/ransack/issues/504

Disclaimer: This is the first time I've ever worked with ransack or arel in detail, and I'm not the one who wrote the ransacker in my app.  I'm just trying to upgrade to the latest ransack (1.6.3).

### CODE REVIEW

**Comment by jaredbeck** [comment]
@jonatack please let me know how you'd like to proceed with this.

**Comment by jaredbeck** [comment]
> let me know how you'd like to proceed

What about a simple solution like `respond_to?(:val)`?

```diff
  def casted_array_with_in_predicate?(predicate)
    return unless defined?(Arel::Nodes::Casted)
    predicate.class == Arel::Nodes::In &&
+     predicate.right[0].respond_to?(:val) &&
      predicate.right[0].val.is_a?(Array)
  end
```

**Comment by jaredbeck** [comment]
If I understand this all correctly, the right-hand side of an `IN` predicate does not always respond to :val.  For example, it might be a subquery, represented by a `SelectManager`.

**Comment by jonatack** [comment]
Thank you, this was helpful in reproducing the issue and I've written a failing/passing spec based on what you've shown above.

OK for the quick fix with `respond_to?` as above or using `try` like `predicate.right[0].try(:val).is_a?(Array)`.

When I get some time I need to dig in and go through the new Arel and AR API changes. There may be a better way of handling these cases.

**Comment by jaredbeck** [comment]
> Thank you, this was helpful 

No problem.  Thank you for being so quick to respond throughout the day!

Like I said, this was my first time working with ransack and arel in any detail and I learned a ton.

**Pull request merged**
