### PR TITLE
make polyamorous a separate gem

### PR DESCRIPTION
**Pull request by gregmolnar**
Let's release polyamorous as a separate gem, as discussed in here: https://github.com/rzane/baby_squeel/issues/97
@rzane once this is merged I will release a new version of polyamorous with support for >= Active Record 5
/cc @seanfcarroll

### CODE REVIEW

**Comment by seanfcarroll** [comment]
Works for me

**Comment by brentdodell** [comment]
Hi @gregmolnar! Thanks for doing this. Any idea when you'll be able to release a new version of [polyamorous](https://rubygems.org/gems/polyamorous)?

**Comment by gregmolnar** [comment]
@brentdodell I want to get this issue sorted before that: https://github.com/activerecord-hackery/ransack/pull/1004
If all goes well, I should be able to find a few hours to get to the bottom of that issue shortly.

**Comment by brentdodell** [comment]
Thanks @gregmolnar!

**Pull request merged**
