### PR TITLE
Added RU locale

### PR DESCRIPTION
**Pull request by sesharim**

### CODE REVIEW

**Comment by pedrofurtado** [comment]
@sesharim Thanks for PR! :tada: 
@gregmolnar I think this PR is OK for merge. But, let us know if something has to be added or changed to make it mergeable :+1:

**Comment by gregmolnar** [comment]
@sesharim Could you please squash the commits?

**Comment by pedrofurtado** [comment]
@gregmolnar It's possible to squash and merge by Github UI, without needing of the author of PR to do it. But I don't know if this repo have this feature enabled in settings.

**Comment by sesharim** [comment]
@pedrofurtado i didn’t find this feature but i definately expected it here. :) It’s quite handy.
@gregmolnar i’m on my way home to do it but i’m not sure i’ll be soon. :(

**Comment by pedrofurtado** [comment]
@sesharim Check this URL: https://help.github.com/articles/configuring-commit-squashing-for-pull-requests/

After configuration, the PR's in your repos appears like this below:

select-squash-and-merge-from-drop-down-menu

**Comment by sesharim** [comment]
@pedrofurtado 
image

**Comment by pedrofurtado** [comment]
@sesharim It only appears for repos that you are **admin**. It's not the case of ransack :+1:

**Comment by sesharim** [comment]
@pedrofurtado i know it, yep, but what about this one? i have to perform squash locally and push it here, correct?

**Comment by gregmolnar** [comment]
@pedrofurtado I didn't know about this feature of github :) 
@sesharim thank you for your contribution!

**Pull request merged**
