### PR TITLE
Fix wrong table aliases (#1217)

### PR DESCRIPTION
**Pull request by oneiros**
I encountered the same issue as reported in #1217 (and possibly in a bunch of other issues as well[^1]).

It was correctly pointed out, that a change in ActiveRecord was responsible. https://github.com/rails/rails/commit/10b36e81a357f8d7fa3665630c4d41c057fe59d9 tried to fix a bug with eager loading that resulted from aliasing a joined table that was (then incorrectly) referenced in a WHERE clause.

The solution (as far as I understand it - I never had to look at that code before and cannot say I understand all of what is going on there) was to cache tables already joined and reuse those joins if possible.

The problem in #1217 is caused by ransack prepopulating table information *before* this deduplication code is run. So there is no way to detect that a JOIN clause with an alias, that would otherwise have been used, fell victim to the deduplication.

My "solution" is a poor one. I simply copied the deduplication logic from ActiveRecord. This should give the same results as ActiveRecord would come up with on its own.

A better solution would of course be to somehow get the table information at a later point in time and/or extract the deduplication logic in AR to be able to reuse this more easily. But I suspect the first approach would take a huge refactoring of ransack and I am not 100% sure if it is even possible. Also, I am not convinced that ActiveRecord currently cleans up references to table aliases that are not being used due to the deduplication correctly. So patches for AR itself might be needed anyways.

---

[^1]: The following issues seem like they could be related: #1238, #1253, #1227, #1153, #1144

### CODE REVIEW

**Comment by oneiros** [comment]
> My "solution" is a poor one. I simply copied the deduplication logic from ActiveRecord.

On second thought: The original implementation of the `table_aliases_for` method that I patched was also just copied from AR. So conceptually my approach is not worse :slightly_smiling_face:

**Comment by deivid-rodriguez** [comment]
Wow, this is so awesome! It's been an unresolved issue for a long time, and biting several people as you point out! Thanks 😍.

I have one question, we even got some regression specs contributed to demonstrate the issue at https://github.com/activerecord-hackery/ransack/pull/1280. Do you think that spec is worth keeping on top of the ones you added, or they are basically duplicates and should be discarded?

**Comment by oneiros** [comment]
Thank you so much for responding so quickly and for the praise :blush: 

> I have one question, we even got some regression specs contributed to demonstrate the issue at https://github.com/activerecord-hackery/ransack/pull/1280. Do you think that spec is worth keeping on top of the ones you added, or they are basically duplicates and should be discarded?

Those seem to be roughly equivalent to what I did (and I wish I had seen them sooner). The main difference seems to be the number of test records created (I used the bare minimum). Other than that it seems to demonstrate the exact same problem and would be redundant. I only had a cursory glance though, I might have missed some nuance there.

**Comment by deivid-rodriguez** [comment]
Awesome, getting this in then, thanks again!

**Pull request merged**
