### PR TITLE
Remove dead MongoDB code

### PR DESCRIPTION
**Pull request by scarroll32**
Closes https://github.com/activerecord-hackery/ransack/issues/1344

### CODE REVIEW

**Comment by scarroll32** [comment]
@deivid-rodriguez could you review this change please.

**Comment by deivid-rodriguez** [comment]
Is this used by https://github.com/activerecord-hackery/ransack-mongoid?

If no, then this is good to go as is without any concerns.

If yes, then this seems also fine anyways given that you [already archived the ransack-mongoid repo back in march](https://github.com/activerecord-hackery/ransack-mongoid/commit/e75d8112b37146991f73548523e7fc3621c407ff), but we consider backwards compatibility, right?

**Comment by scarroll32** [comment]
> If yes, then this seems also fine anyways given that you [already archived the ransack-mongoid repo back in march](https://github.com/activerecord-hackery/ransack-mongoid/commit/e75d8112b37146991f73548523e7fc3621c407ff), but we consider backwards compatibility, right?

@deivid-rodriguez yes this is correct, the repo is archived. There was little interest for this feature, and if this is something that might be wanted in future it would probably make sense to write it from the ground-up for Mongo, IMHO.

**Comment by deivid-rodriguez** [comment]
Ok, you know best the history of this. I think to be strict with backwards compatibility we should ship this with a major version, but other than that looks fine.

**Comment by scarroll32** [comment]
> Ok, you know best the history of this. I think to be strict with backwards compatibility we should ship this with a major version, but other than that looks fine.

That's an excellent point @deivid-rodriguez ! 

Should we hold this (and https://github.com/activerecord-hackery/ransack/pull/1348) until the next version bump, and make it 4.0.0? 

We are currently on a 2 week cycle for version bumps?

**Comment by deivid-rodriguez** [comment]
We were but I lost the rhythm a couple of cycles ago... 😅. We can recover it on Thursday and get 4.0.0 out if it seems fine to you?

**Comment by scarroll32** [comment]
> We were but I lost the rhythm a couple of cycles ago... 😅. We can recover it on Thursday and get 4.0.0 out if it seems fine to you?

Works for me!! 🎸

**Review by deivid-rodriguez — APPROVED** [review]
Alright let's do it!

**Pull request merged**
