### PR TITLE
load 5.2.1 polyamorous files for >= 5.2.1

### PR DESCRIPTION
**Pull request by gregmolnar**

### CODE REVIEW

**Comment by kennyadsl** [comment]
Hey there! 👋 

I think that this is needed in all gems that depend on both Rails and Ransack and are not locking them to a specific version.

Is there any chance to release a new version of the gem with this change?

**Comment by gregmolnar** [comment]
@kennyadsl I will cut a release tomorrow.

**Comment by lucianosousa** [comment]
why you guys just didn't remove the line 15?

**Comment by gregmolnar** [comment]
@lucianosousa 5.2.0 and >= 5.2.1 requires different files to be loaded.

**Pull request merged**
