### PR TITLE
Do not override `join_constraints`

### PR DESCRIPTION
**Pull request by y-yagi**
In the current master, an error occurs when performing a specific join process in AR 5.2.1(My bad!).

Reproduce script is following.

```
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", "5.2.1.rc1"
  gem "byebug"
  gem "ransack", github: "activerecord-hackery/ransack", require: false
  gem "sqlite3"
  # gem "pg"
end

require "active_record"
require "ransack"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table "set_adopted_books", force: :cascade do |t|
    t.bigint "adopted_book_set_id"
  end

  create_table "adopted_book_sets", force: :cascade do |t|
    t.bigint "library_id"
  end

  create_table "libraries", force: :cascade do |t|
  end
end

class SetAdoptedBook < ActiveRecord::Base
  belongs_to :adopted_book_set
end

class AdoptedBookSet < ActiveRecord::Base
  belongs_to :library
  has_many   :set_adopted_books, dependent: :destroy
end

class Library < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_association_stuff
    refute SetAdoptedBook.joins(adopted_book_set: :library).exists?
    # => ActiveRecord::StatementInvalid: SQLite3::SQLException: ambiguous column name: libraries.id: SELECT  1 AS one FROM "set_adopted_books" INNER JOIN "adopted_book_sets" ON "adopted_book_sets"."id" = "set_adopted_books"."adopted_book_set_id" INNER JOIN "libraries" ON "libraries"."id" = "adopted_book_sets"."library_id" INNER JOIN "libraries" ON "libraries"."id" = "adopted_book_sets"."library_id" LIMIT ?
  end
end
```

ransack overrides the join process, and it is an error because there is not enough processing there.
However, it does not seem to be necessary to override the process at the moment. So, I removed the overriding methods.

### CODE REVIEW

**Comment by gregmolnar** [comment]
Rails 5.1.2 has been released for 2 days now, so I don't really get why are you the 3rd person who complains about not having a compatible version of Ransack released. It is not like I am waiting for months to cut a release and thanks to @y-yagi master is working fine so please just use that till I get the time to cut a release. 
I maintain this project in my free time, not getting paid for it, so you probably understand that work and my family gets priority over this.

**Comment by jaredbeck** [comment]
Hi Greg, Sorry if it sounded like a complaint. I'm just concerned that a few hundred people will also lose an hour of their lives troubleshooting this. Yes, they can use `master` but they will still have lost that hour (maybe more, if they're not good at debugging gems). I'm not complaining, just wanted to point out that this issue will affect a lot of people. Thanks for your work on this.

**Comment by gregmolnar** [comment]
@jaredbeck 2.0.0 with Active Record 5.2.1 support has been released. Please give it a spin and let us know if you encounter any issues.

**Comment by jaredbeck** [comment]
> @jaredbeck 2.0.0 with Active Record 5.2.1 support has been released. Please give it a spin and let us know if you encounter any issues.

Thanks for the quick release Greg. I have tested ransack 2.0.0 and I only found one issue, which I have done my best to isolate: https://github.com/activerecord-hackery/ransack/issues/947

**Pull request merged**
