### PR TITLE
Revert "Fixed: Rails 4.2: NoMethodError: undefined method asc for #<Arel::Nod…"

### PR DESCRIPTION
**Pull request by seanfcarroll**
Reverts activerecord-hackery/ransack#600

### CODE REVIEW

**Comment by seanfcarroll** [comment]
Errors on merge to master

**Comment by roman-franko** [comment]
Hi, seanfcarroll.
Could you clarify, please, what exactly errors happened?

**Comment by seanfcarroll** [comment]
Hi @roman-franko it seems to be OK now, possibly as a result of https://github.com/activerecord-hackery/ransack/pull/875

I created a new PR from your repo and have merged it. Will cut the new release of the gem soon, but for now, you can track master.

Thank you for your contributions.

**Comment by roman-franko** [comment]
Ok, thanks!

**Comment by roman-franko** [comment]
Sorry, but it looks like wrong commit in activerecord-hackery/ransack . 
https://github.com/activerecord-hackery/ransack/commit/fa6f8a5f92b7dedf90a206abc9651a8602ed79de

This is the correct one: https://github.com/roman-franko/ransack/commit/c06120b2c3545ba78d4c25c6e88861b2357d2f5a

**Comment by roman-franko** [comment]
Can I fix it by myself?

**Comment by seanfcarroll** [comment]
Sure, just submit a new PR

**Pull request merged**
