### PR TITLE
Code quality improvements

### PR DESCRIPTION
**Pull request by scarroll32**
Extracted from https://github.com/activerecord-hackery/ransack/pull/1348

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
Awesome @scarroll32! Can we enable a RuboCop rule to enforce this style going forward? Happy to add it myself to this PR if that's ok with you!

**Comment by scarroll32** [comment]
> Can we enable a RuboCop rule to enforce this style going forward? Happy to add it myself to this PR if that's ok with you!

That would be awesome @deivid-rodriguez !

**Comment by deivid-rodriguez** [comment]
@scarroll32 Done!

By the way, I noticed a GitHub banner alert about us not having branch protections enabled. Is is intentional?

**Comment by scarroll32** [comment]
> @scarroll32 Done!
> 
> By the way, I noticed a GitHub banner alert about us not having branch protections enabled. Is is intentional?

It's something that flashed up recently. I think it is a paid feature though (although maybe free for FOSS 🤔 )

It would actually be great to have - protect the `main` branch

**Review by deivid-rodriguez — APPROVED** [review]

**Pull request merged**
