### PR TITLE
Failing test cases for when 0 and 1 are passed to non-boolean scopes

### PR DESCRIPTION
**Pull request by gkop**
@avit, may we re-open #504 based on these failing test cases?

### CODE REVIEW

**Comment by avit** [comment]
It looks like this is passing except that your tests expect `HAVING count(articles.id) = 0` but the actual SQL query is quoted for different databases as `HAVING count(articles.id) = 'f'`

See #507

**Comment by avit** [comment]
Ah, never mind. I see this should be an integer count...

**Comment by jaredbeck** [comment]
> @avit, may we re-open #504 based on these failing test cases?

@gkop you meant to say "re-open https://github.com/activerecord-hackery/ransack/pull/503", right?

**Comment by gkop** [comment]
Derp, yes you got it Jared!

**Comment by gkop** [comment]
Actually @jaredbeck I meant #502 !

**Comment by avit** [comment]
Looking at this again after a long while... 

I don't think Ransack should be responsible for converting params anymore, this should probably be happening in the controller anyway. We should probably just support this without getting too clever:

* Array for params passed as arguments, without converting values
* Single value for selecting the scope (truthy/falsy), without arguments

**Comment by seanfcarroll** [comment]
Superseded by https://github.com/activerecord-hackery/ransack/pull/742

**Pull request closed without merging**
