### PR TITLE
Reverse joins to add to fix join order issue

### LINKED ISSUE #1142: Wrong order of joins
Using the following code results in a query where the joins are ordered in a way that causes the query to crash:

```ruby
Contact.ransack(student_councils_subscriptions_id_null: true)
```

Produces the following SQL:
```
SELECT
  "contacts".* 

FROM 
  "contacts" 

LEFT OUTER JOIN "subscriptions" ON 
  "subscriptions"."contact_id" = "student_councils_contacts"."id" 

LEFT OUTER JOIN "contact_relationships" ON 
  "contact_relationships"."relationship_type" = 'student_council' AND 
  "contact_relationships"."parent_id" = "contacts"."id" 

LEFT OUTER JOIN "contacts" "student_councils_contacts" ON 
  "student_councils_contacts"."id" = "contact_relationships"."child_id" 

WHERE 
  "subscriptions"."id" IS NULL
```

This crashes with the following error:
```
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  missing FROM-clause entry for table "student_councils_contacts"
LINE 1: ..."subscriptions" ON "subscriptions"."contact_id" = "student_c...
```

If I manually move the subscriptions-join to the bottom of the query it works as expected:
```
SELECT
  "contacts".* 

FROM 
  "contacts" 

LEFT OUTER JOIN "contact_relationships" ON 
  "contact_relationships"."relationship_type" = 'student_council' AND 
  "contact_relationships"."parent_id" = "contacts"."id" 

LEFT OUTER JOIN "contacts" "student_councils_contacts" ON 
  "student_councils_contacts"."id" = "contact_relationships"."child_id" 

LEFT OUTER JOIN "subscriptions" ON 
  "subscriptions"."contact_id" = "student_councils_contacts"."id" 

WHERE 
  "subscriptions"."id" IS NULL
```

It doesn't seem to be an issue with ActiveRecord, because if I do like this it generates SQL with the correct order:
```
Contact.left_joins(student_councils: :subscriptions).to_sql
```
```
SELECT
  "contacts".* FROM "contacts" 

LEFT OUTER JOIN "contact_relationships" ON 
  "contact_relationships"."relationship_type" = 'student_council' AND 
  "contact_relationships"."parent_id" = "contacts"."id" 

LEFT OUTER JOIN "contacts" "student_councils_contacts" ON 
  "student_councils_contacts"."id" = "contact_relationships"."child_id" 

LEFT OUTER JOIN 
  "subscriptions" ON "subscriptions"."contact_id" = "student_councils_contacts"."id"
```

### PR DESCRIPTION
**Pull request by kaspernj**
Fixes #1142

### CODE REVIEW

**Comment by seanfcarroll** [comment]
@kaspernj thank you for this contribution. 

Would it be possible to add a test that presents the condition described in the original issue?

**Comment by kaspernj** [comment]
@seanfcarroll Yes of course. Please note that I don't regard this pull request for finished (because the lack of a test), which is why it is still a draft :-) 

Should I have used a different method of indicating that it is still a work in progress? :-)

**Comment by seanfcarroll** [comment]
@kaspernj the draft indicator is perfect, thank you. My apologies for jumping the gun 😄

**Comment by kaspernj** [comment]
I simply don't have the insight into Ransack and ActiveRecord to fix this issue unfortunately :'-(

**Pull request closed without merging**
