### PR TITLE
Add spec described in #1153.

### PR DESCRIPTION
**Pull request by MrJoy**
This adds a spec that should demonstrate the issue described in #1153.

### CODE REVIEW

**Comment by MrJoy** [comment]
I'm pretty sure Travis is stuck.  You might need to cancel and restart the build. :-/

**Comment by deivid-rodriguez** [comment]
imagen

:disappointed:

We'll need to migrate away from TravisCI.com. For me Github Actions would the be easiest alternative.

**Comment by yahonda** [comment]
Let me work on enabling GitHub Actions.

**Comment by yahonda** [comment]
Opened https://github.com/activerecord-hackery/ransack/pull/1180 to run CI on GitHub Actions.

**Comment by deivid-rodriguez** [comment]
@MrJoy Can you rebase now on top of the latest master branch, so that the new CI triggers?

**Comment by MrJoy** [comment]
@deivid-rodriguez Will do!

**Comment by MrJoy** [comment]
Ok.  Apologies for the vague spec naming -- couldn't think of anything better.  But.  The issue is being properly demonstrated, so yay!

**Comment by seanfcarroll** [comment]
Thank you @MrJoy !

**Pull request merged**
