### PR TITLE
Add support for sorting by scopes

### PR DESCRIPTION
**Pull request by benlangfeld**
For when we want to sort by something complex such as the result of a SQL function.

**Credit**: This solution was borrowed from [this gist](https://gist.github.com/laserlemon/e5ce4e0d8bac63f4aa6835605ce3ec21).

### CODE REVIEW

**Comment by benlangfeld** [comment]
Please let me know what I can do to help this get into a 2.1.0 release as quickly as possible.

**Comment by benlangfeld** [comment]
Awesome, thanks for merging @seanfcarroll ! Any idea when 2.1.0 might be released? Is there anything I can do to help with that?

**Comment by seanfcarroll** [comment]
That's been released now, cheers @benlangfeld

**Comment by benlangfeld** [comment]
Excellent! Thank you very much @seanfcarroll

**Comment by pnghai** [comment]
Hi, is there any chance this one can be support on 1.8 branch? As our system still on Rails 4. :(

**Comment by simi** [comment]
We have ported this to 1.8 branch since we're still on Rails 4 also (I hope not for long time). Is there any interest from core team to submit this port as a pull request?

**Comment by simi** [comment]
@gregmolnar PR submitted. ^

**Pull request merged**
