### PR TITLE
Enable sort using alias

### PR DESCRIPTION
**Pull request by waldyr**
Duplicates #766 and #1084 but this one have tests. All credit should be given to the PR authors.

### CODE REVIEW

**Comment by seanfcarroll** [comment]
This looks great @waldyr, any chance to add a note to the documentation?

**Comment by waldyr** [comment]
Sure. I just don't know what to add 😆 

The example [here](https://github.com/activerecord-hackery/ransack#ransack-aliases) uses `_or_` so it won't really work with sorting. Should I add another alias on the example and explain that you can use with sort_link or maybe you have something else in mind.

**Comment by seanfcarroll** [comment]
> Should I add another alias on the example and explain that you can use with sort_link

@waldyr this would cover it, thank you.

**Comment by waldyr** [comment]
@seanfcarroll done. Let me know if it's enough

**Comment by seanfcarroll** [comment]
@waldyr that is great, thank you. I'll merge it once the CI has completed.

**Pull request merged**
