### PR TITLE
Cast PostgreSQL's timestamptz columns to time

### PR DESCRIPTION
**Pull request by lucasfais**
Before Rails 7, PostgreSQL's timestamptz columns were handled as `datetime`, but now `type` returns `:timestamptz`:

```
irb(main):181:0> User.columns_hash['created_at'].type
=> :timestamptz
```

I tested this PR's change in my production app, it's working fine, but let me know if this is not the correct/complete fix for the issue.

### CODE REVIEW

**Comment by scarroll32** [comment]
@lucasfais thank you for this PR.

Could you please add a couple of tests?

**Comment by lucasfais** [comment]
@scarroll32 Sure. `Ransack::Nodes::Value` had no specs, so I added basic specs for all types. `:timestamptz` specially is on line 28. Thanks!

**Review by deivid-rodriguez — APPROVED** [review]
Makes sense to me!

**Comment by scarroll32** [comment]
Thank you @lucasfais !

**Pull request merged**
