### PR TITLE
Add changelog for alias_attribute support.

### PR DESCRIPTION
**Pull request by martndemus**

### CODE REVIEW

**Comment by jonatack** [comment]
Thanks! Could you add your name underneath (credit yourself for your work) with `[skip ci]` in the commmit message and squash?

**Comment by martndemus** [comment]
Done!

**Comment by jonatack** [comment]
Nice :100:

**Comment by jonatack** [comment]
And thanks again for the well-done contribution!

**Comment by martndemus** [comment]
This addition to ransack is going to help us so much!

**Comment by jonatack** [comment]
Great. I'll try to get a new patch release out soon, hopefully you can use the master branch in the interim.

**Pull request merged**
