### PR TITLE
Add Japanese yml file

### PR DESCRIPTION
**Pull request by masacandy**
Added Japanese locale.
Hope you like it.

### CODE REVIEW

**Comment by jonatack** [comment]
@masacandy Thanks! Could you update the change log file with your contribution and we'll merge it in.

**Comment by jonatack** [comment]
You can use `[skip ci]` in your commit message so the travis tests don't :runner: needlessly.

**Comment by masacandy** [comment]
@jonatack Thanks for your replay. I updated  the change log (forgot to add `[skip ci]` though...)

**Comment by jonatack** [comment]
Could you push your change log update to the same branch? I don't see it here. Thanks!

**Comment by masacandy** [comment]
I think I had misunderstood... but I did as you want this time probably

**Comment by jonatack** [comment]
All good, thank you @masacandy :shipit:

**Pull request merged**
