### PR TITLE
Add list of predicates to readme

### PR DESCRIPTION
**Pull request by Paxa**
I often open this repo because I don't remember all predicates.
And for some predicates it was not obvious for me how to use it, so I had to search in repo.

I hope this section in README will be helpful for people like me, but probably need some help to make better description.

Also:
- `_eq_any` is same as `_in` ? (and `_not_eq_any` is same as `_not_in`?)
- What's the point to use `eq_all` ? If I use it as `col_eq: ["A", "B"]`, how something can be equal "A" and "B" at the same time?
- What's the point to use `gt_any`? If value in DB is greater then any then it's greater then smallest searchable value?
- Same with `gt_all` - if greater then all, then also greater then biggest
- If I do `start_all: ["A", "B"]`, anything can start with "A" and "B" at the same time?

### CODE REVIEW

**Comment by jonatack** [comment]
Thanks @paxa, did you ever consult the [wiki](https://github.com/activerecord-hackery/ransack/wiki/Basic-Searching)?

**Comment by jonatack** [comment]
Please see also the [CONTRIBUTING.md](https://github.com/activerecord-hackery/ransack/blob/master/CONTRIBUTING.md) about using `[skip ci]` for documentation-only commits. Thanks 😃

**Comment by Paxa** [comment]
Thanks, I added link to wiki too

**Comment by Paxa** [comment]
What do you think? Should it be merged?
Or just publish in wiki?

**Comment by seanfcarroll** [comment]
There is already so much in the README that could also be in a wiki. Moving it into the wiki could be a future PR. Merging this.

**Pull request merged**
