### PR TITLE
Escape underscore wildcard for pg and mysql.

### PR DESCRIPTION
**Pull request by IgorDobryn**
Escape mysql/pg `_` wildcard character.

### CODE REVIEW

**Comment by a-chumagin** [comment]
+1

**Comment by jonatack** [comment]
Thanks!

**Comment by alkuzad** [comment]
+1 when this fix will be released ? It can be potentially dangerous

**Comment by ernie** [comment]
FWIW, back when I built Ransack leaving wildcard matching supported was intentional. I think I even used to have a screencast demoing it. ;)

**Comment by ernie** [comment]
But then, it was intended to be used for admin backends and the like. Folks seem to want to use it for more user-facing stuff than is wise.

**Comment by alkuzad** [comment]
@ernie we faced that in LIKE statements (cont/end) when users can not match underscores, i.e `foo_end:"_bar"` will match anything that has bar at the end, not only the exact `_bar`

Great to know origins of this gem :) With the all that form helpers I always thought it's more user-oriented.

**Comment by jonatack** [comment]
@ernie Interesting! Perhaps keep it as a config option, defaulting to 'safe'?

@alkuzad Yes, it's definitely time to cut a release. Til then, Ransack master works.

**Comment by ernie** [comment]
@jonatack Totally up to you. To be fair, wildcards can return unexpected data but I wouldn't necessarily call them "unsafe". @alkuzad's concern, however, is warranted, in that if someone doesn't understand how to use wildcards, they may get confusing results.

**Comment by alkuzad** [comment]
@ernie even if all our users would be devs they would not be possible to escape them as slash is also escaped :)

**Comment by jonatack** [comment]
Thanks, this provides useful perspective. My own use has been for admin backends only, and more focused on simplicity for the users and fast live response with punctuation stripped out anyway.

**Pull request merged**
