### PR TITLE
Change zh.yml to zh-CN.yml

### PR DESCRIPTION
**Pull request by ethanyoung**
zh is not valid in Rails I18n.

See details in #588.

### CODE REVIEW

**Comment by jonatack** [comment]
Thanks!

**Comment by jonatack** [comment]
Closes #588.

**Comment by jonatack** [comment]
In the future, 2 suggestions:

- Squash your commits down to one single commit for the git history. Not a big deal here on Ransack, but on a project like Rails, for example, they will ask you to squash before merging.

- When your PR fixes an issue, there’s one more little trick that makes it even more awesome:  Add `Closes #XXX.` as the last line of your commit message.  This automatically closes the issue when your PR is merged in :100:

**Comment by ethanyoung** [comment]
Thanks for the suggestions!

On 20 Sep 2015 7:17 am, Jon Atack <notifications@github.com> wrote:
In the future, 2 suggestions:

- Squash your commits down to one single commit for the git history. Not a big deal here on Ransack, but on a project like Rails, for example, they will ask you to squash before merging.

- When your PR fixes an issue, there’s one more little trick that makes it even more awesome:  Add `Closes #XXX.` as the last line of your commit message.  This automatically closes the issue when your PR is merged in :100:

---

**Pull request merged**
